version: '3.4'

services: 
    db:
        container_name: enterprise-notes-db
        image: postgres
        restart: unless-stopped
        environment: 
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: enterprisenotes

        ports: 
            - "5432:5432"
        
    pgadmin:
        container_name: enterprise-notes-pgadmin
        image: dpage/pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root

        ports: 
            - "5050:80"
    
    web:
        build: .

        container_name: enterprise-notes-web
        restart: unless-stopped

        volumes: 
            - "./config.docker.yml:/app/config.yml:ro"

        ports: 
            - "8080:80"